uploads = []

[[generated]]
id = "8wgfxsy9OSWLN7p5AEgxE"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "GsY14iVRPK64MVOnNIkAt"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "Updated app icon"
