import { Router, type IRouter } from "express";
import healthRouter from "./health";
import analyseRouter from "./analyse";
import authRouter from "./auth";
import pipelineTestRouter from "./pipeline-test";
import subscriptionRouter from "./subscription";
import searchesRouter from "./searches";
import exploreRouter from "./explore";
import conversationsRouter from "./conversations";
import storageRouter from "./storage";
import uploadRouter from "./upload";
import listingsRouter from "./listings";
import dmRouter from "./dm";
import usersRouter from "./users";
import notificationsRouter from "./notifications";
import recommendationsRouter from "./recommendations";
import agentContactRouter from "./agent-contact";
import loadingHintRouter from "./loading-hint";
import streetviewRouter from "./streetview";
import staticmapRouter from "./staticmap";
import imageProxyRouter from "./image-proxy";
import otpRouter from "./otp";
import supportRouter from "./support";
import feedbackRouter from "./feedback";
import agentCallEventRouter from "./agent-call-event";
import adminRouter from "./admin";
import stripeRouter from "./stripe";
import sharesRouter from "./shares";
import translateRouter from "./translate";
import transcribeRouter from "./transcribe";
import watchlistRouter from "./watchlist";
import reportPdfRouter from "./report-pdf";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use(analyseRouter);
router.use(pipelineTestRouter);
router.use(subscriptionRouter);
router.use(searchesRouter);
router.use(exploreRouter);
router.use(conversationsRouter);
router.use(storageRouter);
router.use(uploadRouter);
router.use(listingsRouter);
router.use(dmRouter);
router.use(usersRouter);
router.use(notificationsRouter);
router.use(recommendationsRouter);
router.use(agentContactRouter);
router.use(loadingHintRouter);
router.use(streetviewRouter);
router.use(staticmapRouter);
router.use(imageProxyRouter);
router.use(otpRouter);
router.use(supportRouter);
router.use(feedbackRouter);
router.use(agentCallEventRouter);
router.use(adminRouter);
router.use(stripeRouter);
router.use(sharesRouter);
router.use(translateRouter);
router.use(transcribeRouter);
router.use(watchlistRouter);
router.use(reportPdfRouter);

export default router;
